### ISSUE TITLE
Asymmetric algorithm support

### ISSUE THREAD

**Issue by J4NS-R** [Joffcom/n8n-nodes-jwt#2]
Hi, I love this node.

I'm trying to get N8N working with GitHub Apps, but in order to do so I must generate a JWT using the `RS256` algorithm (which is asymmetric). This is a [GitHub Requirement](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app) I can't get around. It would be awesome if this node could support `RS256`.

**Comment by Joffcom** [comment]
Sounds good to me

**Comment by Joffcom** [comment]
Hey @Koellewe,

Can you give the latest release a go and let me know if it works for you, I have done some quick testing with keys and it seems to work locally for me.

**Comment by J4NS-R** [comment]
Thanks for the quick reply! I tried version 0.2.0, but the algorithm drop-down still only lists the HS algorithms.

<img width="530" alt="image" src="https://github.com/Joffcom/n8n-nodes-jwt/assets/14095706/9a739a6f-6acd-46e2-b68e-0750f357da8f">


Confirmed I'm using 0.2.0:

<img width="784" alt="image" src="https://github.com/Joffcom/n8n-nodes-jwt/assets/14095706/c27355b7-a3cb-4ff7-b08a-b94f43c43107">

**Comment by J4NS-R** [comment]
Good news: I was able to get the node producing the JWTs I need by configuring the following:

- I forced the algorithm to `RS256` by making the field an expression that returns the hardcoded string.
- I used the "Advanced claims builder" with the following expression:
```
{
 "exp": {{Math.trunc(new Date().getTime()/1000)+5*60}},
 "iss": "my-app-id",
 "iat": {{Math.trunc(new Date().getTime()/1000)}} 
}
```

The default JWT claim looked like this (which GitHub did not accept):
```
{
  "expiresIn": 600,
  "issuer": "my-app-id",
  "iat": 1691434681
}
```

**Comment by Joffcom** [comment]
Hey @Koellewe,

Could you try a full refresh of the browser or restart the n8n instance? They should be there so could be a cache issue.

**Comment by J4NS-R** [comment]
I tried clearing my browser cache & cookies, and I tried a different browser, but still the same result. I then installed the package on a secondary instance I have running, and on that instance I can see the full list of algorithms!

So it probably is a caching issue. Thanks for your help @Joffcom

**Comment by Joffcom** [comment]
Hey @Koellewe 

That is good to hear, so all is good then I guess and I can get this one closed 🙏
